language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "iojs"
before_script:
  - npm install
script:
  - PATH="node_modules/phantomjs/bin:$PATH" java -jar 3rdparty/selenium-server-standalone-2.48.2.jar -port 4445 2&> selenium.log&
  - node node_modules/gulp/bin/gulp.js everything